# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:                   #  run this workflow on push events
    branches: [ main ]
  pull_request:           #  run this workflow on PR events
    branches: [ main ]
  workflow_dispatch:      #  run this workflow manually from the Actions tab

jobs:
  build-java:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Check Environment
      id: check-env
      run: |
        echo ${{ github.event_name  }}    # push or pull_request
        echo ${{ github.event.pull_request.title  }}    # PR title
        echo ${{ github.base_ref  }}    # Target Branch name used for PR
        echo ${{ github.ref_name  }}    # Branch name used for check-in
        echo ${{ github.repository  }}    # Repository name

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build



     #    - name: Build and Push Docker Image
     #      uses: mr-smithers-excellent/docker-build-push@v4
     #      with:
     #        image: nanajanashia/demo-app
     #        registry: docker.io
     #        username: ${{ secrets.DOCKER_USERNAME }}
     #        password: ${{ secrets.DOCKER_PASSWORD }}

     