# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle
run-name: Build and Test Java Project

on:
  push:                   #  run this workflow on push events
    branches: [ main ]
  
  pull_request:           #  run this workflow on PR events
    branches: [ main ]

  workflow_dispatch:      #  run this workflow manually from the Actions tab
    inputs:
      ENV:
        type: choice
        required: true
        options:
          - DEV
          - QA
          - PROD
        default: 'DEV'

  pull_request_target:  #  When PR closed merged or not
    types:
      - closed



jobs:
  build-java:         #  Job name

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Check Environment
      id: check-env
      run: |
        echo event_name:      ${{ github.event_name  }}                   # push or pull_request
        echo PR Request:      ${{ github.event.pull_request.title  }}     # PR title
        echo base_ref:        ${{ github.base_ref  }}                     # Target Branch name used for PR
        echo ref_name:        ${{ github.ref_name  }}                     # Branch name used for check-in
        echo repo name:       ${{ github.repository  }}                   # Repository name

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build

     #
     #    - name: Build and Push Docker Image
     #      uses: mr-smithers-excellent/docker-build-push@v4
     #      with:
     #        image: nanajanashia/demo-app
     #        registry: docker.io
     #        username: ${{ secrets.DOCKER_USERNAME }}
     #        password: ${{ secrets.DOCKER_PASSWORD }}
     #

  merge_job:    # Job name
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo PR #${{ github.event.number }} has been merged

  close_job:    # Job name        
    if: github.event.pull_request.merged == false
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo PR #${{ github.event.number }} has been closed without being merged
