name: Need and exit Experiment
run-name: Build and Test Java Project


on: [workflow_dispatch]     #  run this workflow manually from the Actions tab

jobs:
  job1:
    name: Job 1
    runs-on: ubuntu-latest

    steps:
    - name: Sleep and Run
      run: |
        echo "Sleeping for 10"
        sleep 10

  job2:
    name: Job 2 with a Failure
    needs: job1           #  Job 2 runs only after Job1 is completed
    runs-on: ubuntu-latest

    steps:
    - name: Dependant is Running
      run: |
        echo "Completed job 2, but triggering failure"  
        exit 1                                          #  Exit with error code

  job3:
    name: Job 3 
    needs: job2       #  Job 3 runs only after Job2 is completed
    runs-on: ubuntu-latest

    steps:
    - name: Will never run
      run: |
        echo "If you can read this, the experiment failed"