name: Invoke by external Client
run-name: Invoke by external Client

on: 
  repository_dispatch:           # External Client Trigger
    type: [ run_my_workflow ]    # Input Type should be run_my_workflow
  
jobs:
  Example-Actions-Job:
    name: Exploring GitHub Actions - External Client invoke
    runs-on: ubuntu-latest

      
    steps:
      # Input to the workflow
      - run: echo "Payload data is ${{ github.event.client_payload}}"
      - run: echo "Payload field is ${{ github.event.client_payload.name}}"

    
