name: Multi-Environment Deployment

on:
  workflow_dispatch:
    inputs:
      environments:
        description: 'Comma-separated list of environments (e.g., dev,npe,prod)'
        required: true
        default: 'dev'

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Convert input to JSON array
        id: set-matrix
        run: |
          INPUTS="${{ github.event.inputs.environments }}"
          ENV_LIST=$(echo "$INPUTS" | awk -F',' '{for(i=1;i<=NF;i++) printf "\"%s\"%s", $i, (i<NF?",":"") }')
          echo "::set-output name=matrix::{\"env\":[$ENV_LIST]}"
        shell: bash

  deploy:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1              # run one job only at any time 
      matrix: ${{ fromJson(needs.build.outputs.matrix) }}
    name: Deploy to ${{ matrix.env }}
    steps:
      - name: Checkout repository                   # path is needed otherwise extra repo directory will be created inside runner
        uses: actions/checkout@v3
        with:
          path: .

      - name: Set firstrun based on environment position
        id: set_firstrun
        run: |
          INPUTS="${{ github.event.inputs.environments }}"
          ENVIRONMENT="${{ matrix.env }}"
          echo "ENVIRONMENT = $ENVIRONMENT"
          echo "INPUTS = $INPUTS"
          echo "== list files under .github/scripts/"
          ls -al .github/scripts/

          echo "== list files under .github/scripts/set-target-env-variables.sh"
          ls -al .github/scripts/set-target-env-variables.sh

          chmod 755 .github/scripts/set-target-env-variables.sh

          echo == 'running .github/scripts/set-target-env-variables.sh "$ENVIRONMENT" "$INPUTS"'
          .github/scripts/set-target-env-variables.sh "$ENVIRONMENT" "$INPUTS"
        shell: bash            # this line should not be inside run
      
      - name: Print firstrun value
        run: echo "firstrun is ${{ steps.set_firstrun.outputs.firstrun }}"
