name: Multi-Environment Deployment

on:
  workflow_dispatch:
    inputs:
      environments:
        description: 'Comma-separated list of environments (e.g., dev,npe,prod)'
        required: true
        default: 'dev'

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Convert input to JSON array
        id: set-matrix
        run: |
          INPUTS="${{ github.event.inputs.environments }}"
          ENV_LIST=$(echo "$INPUTS" | awk -F',' '{for(i=1;i<=NF;i++) printf "\"%s\"%s", $i, (i<NF?",":"") }')
          echo "::set-output name=matrix::{\"env\":[$ENV_LIST]}"
        shell: bash

  deploy:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.build.outputs.matrix) }}
    name: Deploy to ${{ matrix.env }}
    steps:
      - name: Set firstrun based on environment position
        id: set_firstrun
        run: |
          INPUTS="${{ github.event.inputs.environments }}"
          ENVIRONMENT="${{ matrix.env }}"
          echo "ENVIRONMENT = $ENVIRONMENT"
          echo "INPUTS = $INPUTS"
          ls -al ./.github/scripts/          
          ./.github/scripts/set-target-env-variables.sh "$ENVIRONMENT" "$INPUTS"
          shell: bash
      
      - name: Print firstrun value
        run: echo "firstrun is ${{ steps.set_firstrun.outputs.firstrun }}"
