name: Multi2

on:
  workflow_dispatch:
    inputs:
      environments:
        description: 'Comma-separated list of environments (e.g., dev,npe,prod)'
        required: true
        default: 'dev,npe'

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      env_list: ${{ steps.prepare.outputs.env_list }}
    steps:
      - name: Prepare environment list
        id: prepare
        run: |
          #echo "env_list=$(echo '${{ inputs.environments }}' | sed 's/, */,/g' | jq -R -s 'split(",")')" >> $GITHUB_OUTPUT
          #echo "env_list=$(echo "$target_envs" | awk -F',' '{for(i=1;i<=NF;i++) printf "\"%s\"%s", $i, (i<NF?",":"") }')"  >> $GITHUB_OUTPUT
          echo "env_list=$(echo "$CLEANED" | awk -F',' '{printf "["; for(i=1;i<=NF;i++) printf "\"%s\"%s", $i, (i<NF?",":"") ; print "]"}')" >> $GITHUB_OUTPUT

          target_env_input="${{ github.event.inputs.environments }}"
          target_envs="${target_env_input// /}"  # Remove spaces
          env_list=$(echo "$target_envs" | awk -F',' '{for(i=1;i<=NF;i++) printf "\"%s\"%s", $i, (i<NF?",":"") }')
          echo "env_list={\"env\":[${env_list}]}" >> $GITHUB_OUTPUT          

  deploy:
    needs: setup
    runs-on: ubuntu-latest
    env:
      is_first_run_completed: false
    strategy:
      matrix:
        env: ${{ fromJson(needs.setup.outputs.env_list) }}
      max-parallel: 1
    name: Deploy to ${{ matrix.env }}
    steps:
      - name: Check first run
        run: |
          echo "Is first run completed: ${{ env.is_first_run_completed }}"

      - name: Use setup output
        run: |
          echo "Deploying to environment: ${{ matrix.env }}"
          echo "is_first_run_completed=true" >> $GITHUB_ENV
